config/routes.rb
Rails.application.routes.draw do

  #Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_scope :admin_user do
    authenticated :admin_user do
      root 'admin/dashboard#index'
    end
  end

  #User
  devise_for :users, :skip => [:sessions, :registrations, :passwords, :confirmations, :unlocks]

  devise_scope :user do
    authenticated :user do
      root 'projects#index'
    end
    unauthenticated do
      root 'devise/sessions#new'
    end
    post 'create' , :to => 'devise/sessions#create', :as => :user_session
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :projects, shallow: true do
    resources :tasks do
      resources :resource_tasks
      #resources :resources
    end
    resources :group_projects, only: [:index, :new, :create, :destroy]
  end

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :project
  has_many :resources_tasks, class_name: 'ResourceTask'
  has_many :resources, through: :resources_tasks, dependent: :destroy

  enum status: ['En Proceso', 'Pendiente', 'Concluido']
  enum filters: ['Costo', 'Recursos']
  validates :name,  presence: true, length: { maximum: 30 }
  validates :detail, :start_date, :finish_date, :status, presence: true

  def total_price
    total_price = 0
    self.resources_tasks.each do |resource|
      total_price += resource.total
    end
      total_price
  end

  def total_resources
    self.resources.count
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user, only: [:create, :index, :new]
  before_action :correct_task, only: [:destroy]
  before_action :correct_editor, only: [:edit, :update]

  def index
    @project = Project.find(params[:project_id])
    
    case params[:filter].to_i
    when 0
      @tasks = @project.tasks.sort_by(&:total_price).reverse!
    when 1
      @tasks = @project.tasks.sort_by(&:total_resources).reverse!
    else
      @tasks = @project.tasks
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def new
    @project = Project.find(params[:project_id])
    @task = Task.new(project_id: @project.id)
  end

  def create
    @project = Project.find(params[:project_id])
    @task = current_user.tasks.new(task_params)
    if @task.save
      flash[:success] = "Tarea Creada"
      redirect_to project_tasks_path @project
    else
      flash.now[:alert] = @task.errors.full_messages.join("\n")
      render 'new'
    end
  end

  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(task_params)
      flash[:success] = "Tarea Editada"
      redirect_to project_tasks_path @task.project
    else
      render 'edit'
    end
  end

  def destroy
    Task.find(params[:id]).destroy
    flash[:success] = "Tarea Borrada"
    redirect_back(fallback_location: root_path)
  end

  private

  def task_params
    params.require(:task).permit(:name, :detail, :percentage, :start_date, :finish_date, :status, :project_id)
  end

  def correct_user
    @project = current_user.projects.find_by(id: params[:project_id])
    redirect_to root_url if @project.nil?
  end

  def correct_editor
    @project = current_user.projects.find_by(id: Task.find(params[:id]).project)
    redirect_to root_url if @project.nil?
  end

  def correct_task
    @task = current_user.tasks.find_by(id: params[:id])
    redirect_to root_url if @task.nil?
  end




end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task, url: local_assigns[:url]) do |f| %>
  <%= f.hidden_field :project_id %>

  <% if @task.persisted? %>
    <%if  current_user.tasks.find_by(id: @task.id)%>

      <div class="field is-horizontal is-narrow">
        <div class="field-label is-normal">
          <label class="label">Nombre </label>
        </div>
      </div>

      <div class="field is-horizontal is-narrow">
        <div class="field-body">
          <div class="field">
            <p class="control is-expanded">
              <%= f.text_field :name, class: 'input', placeholder: "Nombre" %>
            </p>
          </div>
        </div>
      </div>

      <div class="field is-horizontal is-narrow">
        <div class="field-label is-normal">
          <label class="label">Detalle </label>
        </div>
      </div>

      <div class="field is-horizontal is-narrow">
        <div class="field-body">
          <div class="field">
            <p class="control is-expanded">
              <%= f.text_field :detail, class: 'input', placeholder: "Detalle" %>
            </p>
          </div>
        </div>
      </div>

      <div class="field is-horizontal is-narrow">
      <div class="field-label is-normal">
        <label class="label">Porcentaje </label>
      </div>
    </div>

    <div class="field is-horizontal is-narrow">
      <div class="field-body">
        <div class="field">
          <p class="control is-expanded">
            <%= f.select :percentage, Percentage.percentages, class: 'input' %>
          </p>
        </div>
      </div>
    </div>

      <div class="field is-horizontal is-narrow">
        <div class="field-label is-normal">
          <label class="label">Fecha Inicio </label>
        </div>
      </div>

      <div class="field is-horizontal is-narrow">
        <div class="field-body">
          <div class="field">
            <p class="control is-expanded">
              <%= f.date_select :start_date, :order => [:day, :month, :year], class: 'input' %>
            </p>
          </div>
        </div>
      </div>

      <div class="field is-horizontal is-narrow">
        <div class="field-label is-normal">
          <label class="label">Fecha Final </label>
        </div>
      </div>

      <div class="field is-horizontal is-narrow">
        <div class="field-body">
          <div class="field">
            <p class="control is-expanded">
              <%= f.date_select :finish_date, :order => [:day, :month, :year], class: 'input' %>
            </p>
          </div>
        </div>
      </div>

      <div class="field is-horizontal is-narrow">
        <div class="field-label is-normal">
          <label class="label">Estado </label>
        </div>
      </div>

      <div class="field is-horizontal is-narrow">
        <div class="field-body">
          <div class="field">
            <p class="control is-expanded">
              <%= f.select :status, Project.statuses.keys.map { |w| [w.humanize, w] }, class: 'input' %>
            </p>
          </div>
        </div>
      </div>

    <%elsif !@task.project.group_projects.find_by_user_id(current_user.id).administrator?  && current_user.projects.find_by(id: @task.project)%>

      <div class="field is-horizontal is-narrow">
        <div class="field-label is-normal">
          <label class="label">Estado </label>
        </div>
      </div>

      <div class="field is-horizontal is-narrow">
        <div class="field-body">
          <div class="field">
            <p class="control is-expanded">
              <%= f.select :status, Project.statuses.keys.map { |w| [w.humanize, w] }, class: 'input' %>
            </p>
          </div>
        </div>
      </div>

    <%end %>

  <%else%>

    <div class="field is-horizontal is-narrow">
      <div class="field-label is-normal">
        <label class="label">Nombre </label>
      </div>
    </div>

    <div class="field is-horizontal is-narrow">
      <div class="field-body">
        <div class="field">
          <p class="control is-expanded">
            <%= f.text_field :name, class: 'input', placeholder: "Nombre" %>
          </p>
        </div>
      </div>
    </div>

    <div class="field is-horizontal is-narrow">
      <div class="field-label is-normal">
        <label class="label">Detalle </label>
      </div>
    </div>

    <div class="field is-horizontal is-narrow">
      <div class="field-body">
        <div class="field">
          <p class="control is-expanded">
            <%= f.text_field :detail, class: 'input', placeholder: "Detalle" %>
          </p>
        </div>
      </div>
    </div>

    <div class="field is-horizontal is-narrow">
    <div class="field-label is-normal">
      <label class="label">Porcentaje </label>
    </div>
  </div>

  <div class="field is-horizontal is-narrow">
    <div class="field-body">
      <div class="field">
        <p class="control is-expanded">
          <%= f.select :percentage, Percentage.percentages, class: 'input' %>
        </p>
      </div>
    </div>
  </div>

    <div class="field is-horizontal is-narrow">
      <div class="field-label is-normal">
        <label class="label">Fecha Inicio </label>
      </div>
    </div>

    <div class="field is-horizontal is-narrow">
      <div class="field-body">
        <div class="field">
          <p class="control is-expanded">
            <%= f.date_select :start_date, :order => [:day, :month, :year], class: 'input' %>
          </p>
        </div>
      </div>
    </div>

    <div class="field is-horizontal is-narrow">
      <div class="field-label is-normal">
        <label class="label">Fecha Final </label>
      </div>
    </div>

    <div class="field is-horizontal is-narrow">
      <div class="field-body">
        <div class="field">
          <p class="control is-expanded">
            <%= f.date_select :finish_date, :order => [:day, :month, :year], class: 'input' %>
          </p>
        </div>
      </div>
    </div>

    <div class="field is-horizontal is-narrow">
      <div class="field-label is-normal">
        <label class="label">Estado </label>
      </div>
    </div>

    <div class="field is-horizontal is-narrow">
      <div class="field-body">
        <div class="field">
          <p class="control is-expanded">
            <%= f.select :status, Project.statuses.keys.map { |w| [w.humanize, w] }, class: 'input' %>
          </p>
        </div>
      </div>
    </div>

  <% end %>

  <div class="field is-grouped">
    <div class="control">
      <%= f.submit yield(:button_text), class: "button is-success" %>
    </div>
  </div>

<% end %>

app/views/tasks/_task.html.erb
<tbody>
<tr>

  <td><%= task.name %></td>
  <td id="fixed_td"><%= task.detail %></td>
  <td><%= task.status %></td>
  <td><%= task.total_price %></td>
  <td><%= Percentage.percentages.key(task.percentage) %></td>
  <td><%= task.total_resources %></td>
  <%if @project.group_projects.find_by_user_id(current_user.id).administrator? || task.user.id == current_user.id || current_user.projects.find_by(id: task.project) %>

    <td><%= link_to 'Editar', edit_task_path(task)%></td>
  <%end%>
  <%if @project.group_projects.find_by_user_id(current_user.id).administrator? || task.user.id == current_user.id %>
    <td><%= link_to 'Borrar', task, method: :delete%></td>

  <%end%>
  <td><%= link_to 'Ver Recursos', task_resource_tasks_path(task)%></td>

</tr>
</tbody>

app/views/tasks/edit.html.erb
<% provide(:button_text, 'Guardar') %>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h3 id="negrita">Tareas</h3>

<%= form_tag(project_tasks_path, method: "get", local: true) do %>
  <%= label_tag(:filter, "Filtrar tareas por:") %>
  <%= select_tag(:filter, options_for_select(Task.filters)) %>
  <%= submit_tag("Filtrar") %>
<% end %>

<div class="container">
  <table class="table">
    <thead>
    <td>Nombre</td>
    <td>Detalle</td>
    <td>Estado</td>
    <td>Costo</td>
    <td>Porcentaje</td>
    <td>Recursos</td>
    <td></td>
    <td></td>
    <td></td>
    </thead>
    <%= render @tasks %>
  </table>
</div>

<br>

  <%= link_to 'Crear Tarea', new_project_task_path, class: 'button is-success' %>

app/views/tasks/new.html.erb
<% provide(:button_text, 'Crear Tarea') %>
<%= render 'form', url: project_tasks_path %>