config/routes.rb
Rails.application.routes.draw do

  #Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_scope :admin_user do
    authenticated :admin_user do
      root 'admin/dashboard#index'
    end
  end

  #User
  devise_for :users, :skip => [:sessions, :registrations, :passwords, :confirmations, :unlocks]

  devise_scope :user do
    authenticated :user do
      root 'projects#index'
    end
    unauthenticated do
      root 'devise/sessions#new'
    end
    post 'create' , :to => 'devise/sessions#create', :as => :user_session
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :projects, shallow: true do
    resources :tasks do
      resources :resource_tasks
      #resources :resources
    end
    resources :group_projects, only: [:index, :new, :create, :destroy]
  end

end

app/models/project.rb
class Project < ApplicationRecord
  has_many :group_projects, dependent: :destroy
  has_many :users, through: :group_projects
  has_many :tasks

  enum status: ['En Proceso', 'Pendiente', 'Concluido']
  enum filters: ['Costo','Miembros','Porcentaje']
  validates :name,  presence: true, length: { maximum: 30 }
  validates :detail, :start_date, :finish_date, :status, presence: true

  def total_price
    total_price = 0
    self.tasks.each do |task|
      total_price += task.total_price
    end
     total_price
  end

  def average_percentage
    self.tasks.empty? ? 0 : self.tasks.map(&:percentage).sum / self.tasks.count
  end

  def total_members
    self.group_projects.count
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!
  before_action :admin_user, :except => [:index]
  before_action :correct_user, :except => [:index, :new, :create]

  def index
    @user = current_user
    case params[:filter].to_i
    when 0
      @projects = @user.projects.sort_by(&:total_price).reverse!
    when 1
      @projects = @user.projects.sort_by(&:total_members).reverse!
    when 2
      @projects = @user.projects.sort_by(&:average_percentage).reverse!
    else
      @projects = @user.projects
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save && GroupProject.create(user_id: current_user.id, project_id: @project.id, role: :administrator)
      flash[:success] = "Proyecto Creado"
      redirect_to root_path
    else
      flash.now[:alert] = @project.errors.full_messages.join("\n")
      render 'new'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      flash[:success] = "Proyecto Editado"
      redirect_to root_path
    else
      flash.now[:alert] = @project.errors.full_messages.join("\n")
      render 'edit'
    end
  end

  def destroy
    Project.find(params[:id]).destroy
    flash[:success] = "Proyecto Borrado"
    redirect_to root_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :detail, :start_date, :finish_date, :status)
  end

  def correct_user
    @project = current_user.projects.find_by(id: params[:id])
    redirect_to root_url if @project.nil?
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>

  <div class="field is-horizontal is-narrow">
    <div class="field-label is-normal">
      <label class="label">Nombre </label>
    </div>
  </div>

  <div class="field is-horizontal is-narrow">
    <div class="field-body">
      <div class="field">
        <p class="control is-expanded">
          <%= f.text_field :name, class: 'input', placeholder: "Nombre" %>
        </p>
      </div>
    </div>
  </div>

  <div class="field is-horizontal is-narrow">
    <div class="field-label is-normal">
      <label class="label">Detalle </label>
    </div>
  </div>

  <div class="field is-horizontal is-narrow">
    <div class="field-body">
      <div class="field">
        <p class="control is-expanded">
          <%= f.text_field :detail, class: 'input', placeholder: "Detalle" %>
        </p>
      </div>
    </div>
  </div>

  <div class="field is-horizontal is-narrow">
    <div class="field-label is-normal">
      <label class="label">Fecha Inicio </label>
    </div>
  </div>

  <div class="field is-horizontal is-narrow">
    <div class="field-body">
      <div class="field">
        <p class="control is-expanded">
          <%= f.date_select :start_date, :order => [:day, :month, :year], class: 'input' %>
        </p>
      </div>
    </div>
  </div>

  <div class="field is-horizontal is-narrow">
    <div class="field-label is-normal">
      <label class="label">Fecha Final </label>
    </div>
  </div>

  <div class="field is-horizontal is-narrow">
    <div class="field-body">
      <div class="field">
        <p class="control is-expanded">
          <%= f.date_select :finish_date, :order => [:day, :month, :year], class: 'input' %>
        </p>
      </div>
    </div>
  </div>

  <div class="field is-horizontal is-narrow">
    <div class="field-label is-normal">
      <label class="label">Estado </label>
    </div>
  </div>

  <div class="field is-horizontal is-narrow">
    <div class="field-body">
      <div class="field">
        <p class="control is-expanded">
          <%= f.select :status, Project.statuses.keys.map { |w| [w.humanize, w] }, class: 'input' %>
        </p>
      </div>
    </div>
  </div>

  <div class="field is-grouped">
    <div class="control">
      <%= f.submit yield(:button_text), class: "button is-success" %>
    </div>
  </div>

<% end %>

app/views/projects/_project.html.erb
<tbody>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.status %></td>
    <td><%= project.total_price %></td>
    <td><%= Percentage.percentages.key(project.average_percentage) %></td>
    <td><%= project.total_members %></td>

    <%if project.group_projects.find_by_user_id(current_user.id).administrator? %>

     <td><%= link_to 'Editar', edit_project_path(project)%></td>
      <td><%= link_to 'Borrar', project, method: :delete%></td>
      <td><%= link_to 'Miembros',  project_group_projects_path(project)%></td>
    <%end%>
    <td><%= link_to 'Ver Tareas', project_tasks_path(project)%></td>
  </tr>
</tbody>

app/views/projects/edit.html.erb
<% provide(:button_text, 'Guardar') %>
<%= render 'form', url: task_path %>

app/views/projects/index.html.erb
<h3>Bienvenido</h3>
<h4 id="negrita"> <%=  current_user.name%></h4>
<br>

<h3 id="negrita">Tus Proyectos</h3>

<%= form_tag(projects_path, method: "get", local: true) do %>
  <%= label_tag(:filter, "Filtrar proyectos por:") %>
  <%= select_tag(:filter, options_for_select(Project.filters)) %>
  <%= submit_tag("Filtrar") %>
<% end %>

<div class="container">
  <table class="table">
    <thead>
    <td>Nombre</td>
    <td>Estado</td>
    <td>Costo</td>
    <td>Porcentaje</td>
    <td>Miembros</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    </thead>
    <%= render @projects %>
  </table>
</div>

<br>

<%if current_user.adm? %>
  <%= link_to 'Nuevo Proyecto', new_project_path, class: 'button is-success' %>
<%end%>

app/views/projects/new.html.erb
<% provide(:button_text, 'Crear Proyecto') %>
<%= render 'form' %>