config/routes.rb
Rails.application.routes.draw do

  #Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_scope :admin_user do
    authenticated :admin_user do
      root 'admin/dashboard#index'
    end
  end

  #User
  devise_for :users, :skip => [:sessions, :registrations, :passwords, :confirmations, :unlocks]

  devise_scope :user do
    authenticated :user do
      root 'projects#index'
    end
    unauthenticated do
      root 'devise/sessions#new'
    end
    post 'create' , :to => 'devise/sessions#create', :as => :user_session
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :projects, shallow: true do
    resources :tasks do
      resources :resource_tasks
      #resources :resources
    end
    resources :group_projects, only: [:index, :new, :create, :destroy]
  end

end

app/models/resource_task.rb
class ResourceTask < ApplicationRecord
    belongs_to :resource
    belongs_to :task
end

app/controllers/resource_tasks_controller.rb
class ResourceTasksController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user, only: [:create, :index, :new]

  def index
    @task = Task.find(params[:task_id])
    @resources = @task.resources_tasks
  end

  def new
    @resources = Resource.all# este hace la busqueda
  end

  def create
    @task = Task.find(params[:task_id])
    @resource = Resource.find(params[:resource_id])
    quantity = params[:quantity]
    total = @resource.price * quantity.to_i
    @resource_task = ResourceTask.create task: @task, resource: @resource, quantity: quantity, total: total
    if @resource_task.save
      flash[:success] = "Recurso Agregado"
      redirect_to  task_resource_tasks_path @task
    else
      flash.now[:alert] = @resources.errors.full_messages.join("\n")
      render 'new'
    end
  end

  def edit
    @resource = ResourceTask.find(params[:id])
  end

  def update
    @resource_task = ResourceTask.find(params[:id])
    @resource = Resource.find(params[:resource_task][:resource_id])
    params[:resource_task].merge!(total: @resource.price.to_i * params[:resource_task][:quantity].to_i)
    if @resource_task.update_attributes(resource_params)
      flash[:success] = "Recurso Editado"
      redirect_to task_resource_tasks_path @resource_task.task
    else
      flash.now[:alert] = @resource_task.errors.full_messages.join("\n")
      render 'edit'
    end
  end

  def destroy
    @resource = ResourceTask.find(params[:id])
    @resource.destroy
    flash[:success] = "Recurso Borrado"
    redirect_back(fallback_location: root_path)
  end

  private

  def resource_params
    params.require(:resource_task).permit(:resource_id, :quantity, :total)
  end

  def correct_user
    @project = current_user.projects.find_by(id: Task.find(params[:task_id]).project)
    redirect_to root_url if @project.nil?
  end

end

app/views/resource_tasks/_form.html.erb
<%= form_with url: task_resource_tasks_path do |f| %>

<div class="field is-horizontal is-narrow">
  <div class="field-label is-normal">
    <label class="label"> Tipo de Miembro </label>
      <%= select_tag(:resource_id, options_from_collection_for_select(@resources, :id, :name)) %>
  </div>
</div>

<div class="field is-horizontal is-narrow">
<div class="field-label is-normal">
  <label class="label">Cantidad de Horas </label>
</div>
</div>

<div class="field is-horizontal is-narrow">
<div class="field-body">
  <div class="field">
    <p class="control is-expanded">
      <%= f.number_field :quantity, class: 'input', placeholder: "Cantidad" %>
    </p>
  </div>
</div>
</div>

<br>

<div class="field is-grouped">
<div class="control">
  <%= f.submit 'Agregar Recurso', class: "button is-success" %>
</div>
</div>

<% end %>

app/views/resource_tasks/_resource_task.html.erb
<tbody>
<tr>
  <td><%= resource_task.resource.name %></td>
  <td><%= resource_task.quantity %></td>
  <td><%= resource_task.total %></td>
  <%if @task.user.id == current_user.id || @task.project.group_projects.find_by_user_id(current_user.id).administrator? %>
    <td><%= link_to 'Editar', edit_resource_task_path(resource_task) %></td>
    <td><%= link_to 'Borrar', resource_task_path(resource_task), method: :delete %></td>
  <%end%>
</tr>
</tbody>

app/views/resource_tasks/edit.html.erb
<%= form_for @resource, url: resource_task_path , method: :put do |f| %>

<div class="field is-horizontal is-narrow">
  <div class="field-label is-normal">
    <label class="label"> Tipo de Miembro </label>
      <%= f.collection_select(:resource_id, Resource.all, :id, :name) %>
  </div>
</div>

<div class="field is-horizontal is-narrow">
<div class="field-label is-normal">
  <label class="label">Cantidad de Horas </label>
</div>
</div>

<div class="field is-horizontal is-narrow">
<div class="field-body">
  <div class="field">
    <p class="control is-expanded">
      <%= f.number_field :quantity, class: 'input', placeholder: "Cantidad" %>
    </p>
  </div>
</div>
</div>

<br>

<div class="field is-grouped">
<div class="control">
  <%= f.submit 'Guardar', class: "button is-success" %>
</div>
</div>

<% end %>

app/views/resource_tasks/index.html.erb
<h3 id="negrita">Recursos</h3>

<div class="container">
  <table class="table">
    <thead>
    <td>Nombre</td>
    <td>Cantidad</td>
    <td>Total</td>
    <td></td>
    <td></td>
    </thead>
    <%= render @resources %>
  </table>
</div>

<br>
  <%= link_to 'Agregar Recurso', new_task_resource_task_path, class: 'button is-success' %>

app/views/resource_tasks/new.html.erb
<% provide(:button_text, 'Agregar Recurso') %>
<%= render 'form', url: task_resource_tasks_path %>