config/routes.rb
Rails.application.routes.draw do

  #Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_scope :admin_user do
    authenticated :admin_user do
      root 'admin/dashboard#index'
    end
  end

  #User
  devise_for :users, :skip => [:sessions, :registrations, :passwords, :confirmations, :unlocks]

  devise_scope :user do
    authenticated :user do
      root 'projects#index'
    end
    unauthenticated do
      root 'devise/sessions#new'
    end
    post 'create' , :to => 'devise/sessions#create', :as => :user_session
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :projects, shallow: true do
    resources :tasks do
      resources :resource_tasks
      #resources :resources
    end
    resources :group_projects, only: [:index, :new, :create, :destroy]
  end

end

app/views/resources/_form.html.erb
<%= form_with url: task_resources_path do |f| %>

<div class="field is-horizontal is-narrow">
  <div class="field-label is-normal">
    <label class="label"> Tipo de Miembro </label>
      <%= f.collection_select(:resource_id, @resources, :id, :name) %>
  </div>
</div>

<div class="field is-horizontal is-narrow">
<div class="field-label is-normal">
  <label class="label">Cantidad de Horas </label>
</div>
</div>

<div class="field is-horizontal is-narrow">
<div class="field-body">
  <div class="field">
    <p class="control is-expanded">
      <%= f.number_field :quantity, class: 'input', placeholder: "Cantidad" %>
    </p>
  </div>
</div>
</div>

<br>

<div class="field is-grouped">
<div class="control">
  <%= f.submit 'Agregar Recurso', class: "button is-success" %>
</div>
</div>

<% end %>

app/views/resources/index.html.erb
<h3 id="negrita">Recursos</h3>

<div class="container">
  <table class="table">
    <thead>
    <td>Nombre</td>
    <td>Cantidad</td>
    <td>Total</td>
    <td></td>
    <td></td>
    </thead>
    <%= render @resources %>
  </table>
</div>

<br>
  <%= link_to 'Agregar Recurso', new_task_resource_path, class: 'button is-success' %>